services:
  colorsurvey-postgres:
    image: postgres:18-alpine
    container_name: colorsurvey-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colorsurvey
    ports:
      - "5433:5432"
    volumes:
      - ./data/pg_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
